### PR TITLE
Rewritten core of SER parser & add support of lossy "*.mov" format

### PR DESCRIPTION
**Pull request by deix**
Hi Rolf,

I have just started rewriting the SER implementation in PSS, and found out that OpenCV supports the MOV file format "out of the box". Thic could be relevant for users using e.g. Canon DSLR for capturing.

Best regards
Michal

### CODE REVIEW

**Comment by Rolf-Hempel** [comment]
Hi Michal,

Good to read that you resumed work on PSS. The most urgent task is to make the VideoReader implementation compliant with the specification. Next on the list would be the debayer functionality.

Half a year ago we discussed whether it would be a good idea to support .mov as well. In your opinion this would be problematic because the compression artifacts could degrade the stacking quality. I still think that this is a valid argument, so I very much hesitate to include .mov now. Have you changed your mind on this issue in the meantime?

Best Regards,
 Rolf

**Comment by deix** [comment]
Hi Rolf,

I just finished rewriting the code of SER parser - now it is finally compatible with the "data buffering" functionality of PSS. The next step for me will be implementing custom debayer functionality for SER files.

P.S. In relation to ".mov" files - I have found some old files made with 8" SCT and my Canon, which I wanted to "process" using PSS...So I added this temporary, but maybe, at the end of the day, the ability of importing the MOV files by PSS would be beneficial for some users, even thoug that this is a lossy file format.

Best regards
Michal

**Comment by Rolf-Hempel** [comment]
Hi Michal,

It's great news that you changed the VideoReader class to make it compliant with the specfication. I tried to merge the changes into "prototype", but Github tells me that "this branch has conflicts that must be resolved". Do you have any idea what I can do?`

All the best,
 Rolf

**Comment by deix** [comment]
Hi Rolf,

I have just pushed the code directly to "prototype" branch.

Best regards
Michal

**Pull request closed without merging**
