### PR TITLE
Prototype

### PR DESCRIPTION
**Pull request by jscheidtmann**
Hi Rolf, here's the change again for using black/white images for planetary alignment. For me this gives better results with my rather noisy Jupiter images. This time the pull request is against prototype.

### CODE REVIEW

**Comment by jscheidtmann** [comment]
Here are some outputs:

- JupA_defaultAlgo: The default center of mass alignment algo using gray scale images (out of the box from prototype, master stops with an error). 

JupA_defaultAlgo
JupA_defaultAlgo stacked

- JupA_bwAlgo_defThreshold: My bw Algo using the default 10*256 threshold.

JupA_bwAlgoHalf
JupA_bwAlgo_defThreshold stacked

**Comment by Rolf-Hempel** [comment]
Hi Jens,

Thank you for re-targeting the pull request at the "prototype" branch. Your proposal seems reasonable to me, Before I accept the pull request, however, I will look carefully into possible side effects. Unfortunately, however, this will take some time because at the moment I'm quite busy with preparing presentations for the 50th anniversary of the first moon landing. PSS has to wait until I'm done with that. Sorry!

Best wishes,
 Rolf

**Comment by Rolf-Hempel** [comment]
Hi Jens,

Finally I found the time to look into the frame alignment issue. I decided to follow your first approach, i.e. to set the threshold at half the maximum brightness. If the overall brightness changes during the video, taking a fixed threshold would shift the relative threshold between frames, such that different parts of the image were included. This could lead to large errors.

Instead of just merging the pull request, I edidted the source files. In particular, I added a static method to compute the COG. This lookks cleaner to me.

I tried the new code with both the large Jupiter and Saturn test videos. It worked just fine with both of them. For all frames the shifts were very close to the values computed with the old algorithm, so I don't mind switching to your proposed algorithm. After all, it seems that with some videos this algorithm is more stable.

There is a minor issue with your proposed use of the SortKey class of module pstats. This only works with Python 3.7. I'm developing PSS using Python 3.5 so far. Therefore, your test program does not work for me.

Thank you very much for your contribution! I will close the pull request now.

All the best,
 Rolf

**Comment by jscheidtmann** [comment]
Hi Rolf,

could you also add the CONTRIBUTING.md?

Thanks,

Jens

**Pull request closed without merging**
